########################
# Spring boot properties
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
########################

spring:
  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://droll-rabbit-5432.7tt.cockroachlabs.cloud:26257/Ponti-reparte?sslmode=verify-full&sslrootcert=C:\\Users\\ivanm\\AppData\\Roaming\\postgresql\\root.crt
    username: nidhood
    password: O48I9g5pHcqxZN_imIsH0w

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.CockroachDB201Dialect
    show-sql: false

server:
  port: 8080